name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Lint & Type Check
        run: |
          npm run lint
          npm run build

      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Push to Google Cloud (on main)
        if: github.ref == 'refs/heads/main'
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://gcr.io
          docker tag my-app gcr.io/$GOOGLE_PROJECT_ID/my-app
          docker push gcr.io/$GOOGLE_PROJECT_ID/my-app

      - name: Deploy to Cloud Run
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy my-app --image gcr.io/$GOOGLE_PROJECT_ID/my-app --platform managed --region us-central1 --allow-unauthenticated
